### ISSUE TITLE
fox example does not work?

### ISSUE THREAD

**Issue by pwais** [NVlabs/instant-ngp#1]
Thanks for posting this amazing work!

I tried to run the fox example and it gives an error with a string ("total must not be zero") that I can't find in the repo so very hard to debug:
```
$ python3 scripts/run.py --scene=data/nerf/fox --mode=nerf
05:31:06 INFO     Loading NeRF dataset from
05:31:06 INFO       data/nerf/fox/transforms.json
Traceback (most recent call last):
  File "scripts/run.py", line 109, in <module>
    testbed.load_training_data(scene)
ValueError: Progress: total must not be zero.
```

The build seems ok tho, this raises a pybind-translated runtime error as expected:
```
$ python3 scripts/run.py --scene=data/nerf/foxx --mode=nerf
Traceback (most recent call last):
  File "scripts/run.py", line 109, in <module>
    testbed.load_training_data(scene)
RuntimeError: Data path 'data/nerf/foxx' does not exist.
```

I tried getting the standard nerf_synthetic lego scene and that seems to work:
```
$ python3 scripts/run.py --scene=data/nerf_synthetic/lego/ --mode=nerf
05:35:03 INFO     Loading NeRF dataset from
05:35:03 INFO       data/nerf_synthetic/lego/transforms_val.json
05:35:03 INFO       data/nerf_synthetic/lego/transforms_test.json
05:35:03 INFO       data/nerf_synthetic/lego/transforms_train.json
05:35:03 SUCCESS  Loaded 400 images of size 800x800 after 0s
05:35:03 INFO       cam_aabb=[min=[0.5,0.5,0.5], max=[0.5,0.5,0.5]]
05:35:03 INFO     Loading network config from: /opt/instant-ngp/configs/nerf/base.json
05:35:03 INFO     GridEncoding:  Nmin=16 b=1.38191 F=2 T=2^19 L=16
05:35:03 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
05:35:03 INFO     Color model:   3--[SphericalHarmonics]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
05:35:03 INFO       total_encoding_params=12196240 total_network_params=10240
...
```

**Comment by pwais** [comment]
thank you @mmalex !  confirmed working with https://github.com/NVlabs/instant-ngp/pull/5
