### ISSUE TITLE
Detectron2 for Windows?

### ISSUE THREAD

**Issue by felixgeen** [NVlabs/instant-ngp#1199]
I cannot get Detectron2 to install, presumably because I am using Windows? Will there be a future update where there is an alternative tool that works with Windows?
Would be very cool!

```
Detectron2 is not installed. Press enter to install it.
Collecting git+https://github.com/facebookresearch/detectron2.git
  Cloning https://github.com/facebookresearch/detectron2.git to c:\users\\appdata\local\temp\pip-req-build-_idwv5xj
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\\AppData\Local\Temp\pip-req-build-_idwv5xj'
  Resolved https://github.com/facebookresearch/detectron2.git to commit 58e472e076a5d861fdcf773d9254a3664e045bf8
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\\AppData\Local\Temp\pip-req-build-_idwv5xj\setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "C:\Users\\instant-ngp\scripts\colmap2nerf.py", line 397, in <module>
    import detectron2
ModuleNotFoundError: No module named 'detectron2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\instant-ngp\scripts\colmap2nerf.py", line 402, in <module>
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
  File "C:\Users\\anaconda3\envs\ngp\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\\\anaconda3\\envs\\ngp\\python.exe', '-m', 'pip', 'install', 'git+https://github.com/facebookresearch/detectron2.git']' returned non-zero exit status 1.
```

**Comment by jdiazram** [comment]
Hi, how do you use detectron2 in instant-ngp? What is the command?
Thx
