### ISSUE TITLE
cutlass_matmul.h:332 status failed with error Error Internal

### ISSUE THREAD

**Issue by DuVogel87** [NVlabs/instant-ngp#1219]
Hello everyone!

I've downloaded Instant-NGP-for-GTX-1000 and when I start to run it via Windows PowerShell I get the following Error, which seems not to be solved currently by anybody. 

If you could be so kind and help me to figure it out, I would be very thankful. 

The output in the console is as followed: 

`PS C:\Users\Denis\Desktop\Instant-NGP-for-GTX-1000> .\instant-ngp.exe .\data\nerf\fox\
11:52:21 SUCCESS  Initialized CUDA. Active GPU is #0: NVIDIA GeForce GTX 1070 Ti [61]
11:52:21 INFO     Loading NeRF dataset from
11:52:21 INFO       .\data\nerf\fox\transforms.json
11:52:21 SUCCESS  Loaded 50 images after 0s
11:52:21 INFO       cam_aabb=[min=[1.0229,-1.33309,-0.378748], max=[2.46175,1.00721,1.41295]]
11:52:21 WARNING  Vulkan error: loader_validate_device_extensions: Device extension VK_NVX_binary_import not supported by selected physical device or enabled layers.
11:52:21 WARNING  Vulkan error: vkCreateDevice: Failed to validate extensions in list
11:52:21 WARNING  Could not initialize Vulkan and NGX. DLSS not supported. (D:\a\instant-ngp\instant-ngp\src\dlss.cu:365 vkCreateDevice(vk_physical_device, &device_create_info, nullptr, &vk_device) failed)
11:52:21 INFO     Loading network config from: .\configs\nerf\base.json
11:52:21 INFO     GridEncoding:  Nmin=16 b=1.51572 F=2 T=2^19 L=16
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
Warning: FullyFusedMLP is not supported for the selected architecture 61. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
11:52:21 INFO     Density model: 3--[HashGrid]-->32--[FullyFusedMLP(neurons=64,layers=3)]-->1
11:52:21 INFO     Color model:   3--[Composite]-->16+16--[FullyFusedMLP(neurons=64,layers=4)]-->3
11:52:21 INFO       total_encoding_params=13074912 total_network_params=10240
**11:52:22 ERROR    Uncaught exception: D:/a/instant-ngp/instant-ngp/dependencies/tiny-cuda-nn/include\tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal**
PS C:\Users\Denis\Desktop\Instant-NGP-for-GTX-1000>`

**Comment by nalim2** [comment]
Hello everybody :)

i get a very similliar issue while i try to adaped the jupyter-notebook file and run the system without a UI.

Here would be my output for try to start the run.py

14:24:46 SUCCESS  Initialized CUDA. Active GPU is #0: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS  Detected auxiliary GPUs:
14:24:47 SUCCESS    #1: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS    #2: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS    #3: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS    #4: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS    #5: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS    #6: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 SUCCESS    #7: NVIDIA GeForce RTX 2080 Ti [75]
14:24:47 INFO     Loading NeRF dataset from
14:24:47 INFO       /home/jovyan/work/instant-ngp/notebooks/video/transforms.json
14:24:47 PROGRESS [                                       ]   0% ( 0/25)  0s/inf14:24:47 PROGRESS [==>                                      ]   4% ( 1/25) 0s/1s14:24:47 PROGRESS [===>                                     ]   8% ( 2/25) 0s/0s14:24:47 PROGRESS [=====>                                   ]  12% ( 3/25) 0s/0s14:24:47 PROGRESS [=======>                                 ]  16% ( 4/25) 0s/0s14:24:47 PROGRESS [========>                                ]  20% ( 5/25) 0s/0s14:24:47 PROGRESS [==========>                              ]  24% ( 6/25) 0s/0s14:24:47 PROGRESS [===========>                             ]  28% ( 7/25) 0s/0s14:24:47 PROGRESS [=============>                           ]  32% ( 8/25) 0s/0s14:24:47 PROGRESS [===============>                         ]  36% ( 9/25) 0s/0s14:24:47 PROGRESS [================>                        ]  40% (10/25) 0s/0s14:24:47 PROGRESS [==================>                      ]  44% (11/25) 0s/0s14:24:47 PROGRESS [====================>                    ]  48% (12/25) 0s/0s14:24:47 PROGRESS [=====================>                   ]  52% (13/25) 0s/0s14:24:47 PROGRESS [=======================>                 ]  56% (14/25) 0s/0s14:24:47 PROGRESS [=========================>               ]  60% (15/25) 0s/0s14:24:47 PROGRESS [==========================>              ]  64% (16/25) 0s/0s14:24:47 PROGRESS [============================>            ]  68% (17/25) 0s/0s14:24:47 PROGRESS [==============================>          ]  72% (18/25) 0s/0s14:24:47 PROGRESS [===============================>         ]  76% (19/25) 0s/0s14:24:47 PROGRESS [=================================>       ]  80% (20/25) 0s/0s14:24:47 PROGRESS [==================================>      ]  84% (21/25) 0s/0s14:24:47 PROGRESS [====================================>    ]  88% (22/25) 0s/0s14:24:47 PROGRESS [======================================>  ]  92% (23/25) 0s/0s14:24:47 PROGRESS [=======================================> ]  96% (24/25) 0s/0s14:24:47 PROGRESS [=========================================] 100% (25/25) 0s/0s14:24:47 SUCCESS  Loaded 25 images after 0s
14:24:47 INFO       cam_aabb=[min=[1.27657,-0.348987,0.00428447], max=[1.73063,0.368763,1.09568]]
Training:   0%|                                      | 0/2000 [00:00<?, ?step/s]14:24:48 INFO     Loading network config from: /home/jovyan/work/instant-ngp/notebooks/instant-ngp/configs/nerf/base.json
14:24:48 INFO     GridEncoding:  Nmin=16 b=1.82344 F=2 T=2^19 L=16
14:24:48 INFO     Density model: 3--[HashGrid]-->32--[CutlassMLP(neurons=64,layers=3)]-->1
14:24:48 INFO     Color model:   3--[Composite]-->16+16--[CutlassMLP(neurons=64,layers=4)]-->3
14:24:48 INFO       total_encoding_params=14008608 total_network_params=10240
Training:   0%|                                      | 0/2000 [00:00<?, ?step/s]
Traceback (most recent call last):
  File "/home/jovyan/work/instant-ngp/notebooks/instant-ngp/./scripts/run.py", line 183, in <module>
    while testbed.frame():
RuntimeError: /home/jovyan/work/instant-ngp/notebooks/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal

With the following device and driver setup: 

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:05:00.0 Off |                  N/A |
| 27%   24C    P8    19W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:06:00.0 Off |                  N/A |
| 27%   23C    P8    11W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  On   | 00000000:43:00.0 Off |                  N/A |
| 27%   21C    P8    21W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce ...  On   | 00000000:44:00.0 Off |                  N/A |
| 27%   23C    P8     4W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA GeForce ...  On   | 00000000:87:00.0 Off |                  N/A |
| 27%   23C    P8     1W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA GeForce ...  On   | 00000000:88:00.0 Off |                  N/A |
| 27%   23C    P8    13W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA GeForce ...  On   | 00000000:C3:00.0 Off |                  N/A |
| 27%   23C    P8    11W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA GeForce ...  On   | 00000000:C4:00.0 Off |                  N/A |
| 27%   23C    P8     1W / 260W |      8MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by MechanicalWhispers** [comment]
> ERROR Uncaught exception: D:/a/instant-ngp/instant-ngp/dependencies/tiny-cuda-nn/include\tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal

I am having this same error after unzipping Instant-NGP-for-GTX-1000 and running the exe, when trying to drop the "fox" folder dataset into the GUI. I'm not a programmer, so I don't know if I am supposed to install anything else? I have a GTX 1080 and a GTX 1060, Open GL version 4.6.0, NVIDIA 528.49, and installed CUDA Toolkit 11.6. Can someone help with a solution to get started?

**Comment by tom-bu** [comment]
I had to use a newer GPU to get it to work > 70 (RTX 2080). Previously used 65 (Titan X)

**Comment by MechanicalWhispers** [comment]
Same. I tried it on a 3090, and it works fine. Must be an issue with the 1000 build? No idea.

**Comment by weizhenFrank** [comment]
I have the exact same issue too. I have TITAN RTX with CUDA 11.4 and NVIDIA 470.161.03

**Comment by tianxiaguixin002** [comment]
I have the same issue too:

RuntimeError: /tmp/pip-req-build-8lb16wz7/include/tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal

Killed

My GPU is P100*4, driver is 510.39.01, CUDA11.3, ubuntu18.04，when code begins, log show following info:
Warning: FullyFusedMLP is not supported for the selected architecture 60. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.

So the GPU is too old for latest tiny-cuda-nn ?

**Comment by lee218llnl** [comment]
Any updates on this? We are seeing the same error on a PPC64LE system with V100's and an X64_64 system with P100s.

**Comment by weizhenFrank** [comment]
I have solved this problem, please try to use the python bindings script

**Comment by lee218llnl** [comment]
I still get the error with the python bindings:

> (opence-1.8.0) bash-4.2$ python scripts/run.py data/nerf/fox/
15:04:54 SUCCESS  Initialized CUDA. Active GPU is #0: Tesla V100-SXM2-16GB [70]
15:05:53 SUCCESS  Detected auxiliary GPUs:
15:05:53 SUCCESS    #1: Tesla V100-SXM2-16GB [70]
15:05:53 SUCCESS    #2: Tesla V100-SXM2-16GB [70]
15:05:53 SUCCESS    #3: Tesla V100-SXM2-16GB [70]
15:05:53 INFO     Loading NeRF dataset from
15:05:53 INFO       data/nerf/fox/transforms.json
15:05:53 SUCCESS  Loaded 50 images after 0s
15:05:53 INFO       cam_aabb=[min=[1.0229,-1.33309,-0.378748], max=[2.46175,1.00721,1.41295]]
Training:   0%|                                     | 0/35000 [00:00<?, ?step/s]15:05:54 INFO     Loading network config from: /usr/WS2/testnewm/delete/opence-1.8.0/instant-ngp/configs/nerf/base.json
15:05:54 INFO     GridEncoding:  Nmin=16 b=2.43803 F=4 T=2^19 L=8
15:05:54 INFO     Density model: 3--[HashGrid]-->32--[CutlassMLP(neurons=64,layers=3)]-->1
15:05:54 INFO     Color model:   3--[Composite]-->16+16--[CutlassMLP(neurons=64,layers=4)]-->3
15:05:54 INFO       total_encoding_params=12855296 total_network_params=10240
Training:   0%|                                     | 0/35000 [00:00<?, ?step/s]
Traceback (most recent call last):
  File "/usr/WS2/testnewm/delete/opence-1.8.0/instant-ngp/scripts/run.py", line 182, in <module>
    while testbed.frame():
RuntimeError: /usr/workspace/testnewm/delete/opence-1.8.0/instant-ngp/dependencies/tiny-cuda-nn/include/tiny-cuda-nn/cutlass_matmul.h:332 status failed with error Error Internal

**Comment by weizhenFrank** [comment]
I built the program specifying the the arch of GPU, and then ran with python script. I recommend you build by specifying the arch version like me.

```
TCNN_CUDA_ARCHITECTURES=75 cmake . -B build  # for TITAN RTX
cmake --build build --config RelWithDebInfo -j 
```

**Comment by weizhenFrank** [comment]
Yes, try to set TCNN_CUDA_ARCHITECTURES equals the GPU arch version that you use rather than 75?

**Comment by lee218llnl** [comment]
My first error report was with arch set to 70, so unfortunately that does not work. My suspicion is that there is a bug somewhere with arch <= 70 that someone needs to debug and fix.

**Comment by weizhenFrank** [comment]
Yes, I think it's a bug for the old version of GPU

**Comment by mgisellef** [comment]
With help from the NVIDIA team (Thank you Matt Stack),  @lee218llnl and I could solve this issue (cutlass_matmul.h:332 status failed with error Error Internal) by running "export CUDA_VISIBLE_DEVICES=0" before running ./instant-ngp --no-gui ./data/nerf/fox/ on our computer with NVIDIA Tesla's V100 16GB GPUs. I hope it is helpful for you too.

**Comment by lee218llnl** [comment]
> With help from the NVIDIA team (Thank you Matt Stack), @lee218llnl and I could solve this issue (cutlass_matmul.h:332 status failed with error Error Internal) by running "export CUDA_VISIBLE_DEVICES=0" before running ./instant-ngp --no-gui ./data/nerf/fox/ on our computer with NVIDIA Tesla's V100 16GB GPUs. I hope it is helpful for you too.

I will add the detail that setting CUDA_VISIBLE_DEVIICES=0 allowed instant-ngp to run without error on our ppc64le + V100 system when built with nvcc -DNGP_BUILD_WITH_GUI=OFF as @mgisellef stated. When I set that env var on our x86 + p100 system, I still get the "Error Internal". On our x86 + p100 system I built with the GUI on and get the error even when I run `instant-ngp --no-gui data/nerf/fox`. The GUI does work by itself when I run `instant-ngp` without specifying any input.

**Comment by chord1412077** [comment]
I have found a solution to the problem: disable the excess graphics card and ensure that only one graphics card is working when you run instant ngp for GTX-1000

**Comment by chord1412077** [comment]
Believe me

**Comment by chord1412077** [comment]
@nalim2

**Comment by chord1412077** [comment]
@nalim2 I have found a solution to the problem: disable the excess graphics card and ensure that only one graphics card is working when you run instant ngp for GTX-1000

**Comment by chord1412077** [comment]
![image](https://user-images.githubusercontent.com/76624203/234499948-1752e7b6-dd62-438e-8f21-710075d63ea0.png)

**Comment by chord1412077** [comment]
before：
![image](https://user-images.githubusercontent.com/76624203/234500568-57a452a9-cbd9-499f-9c1a-d43de983c27c.png)
then it works：
![image](https://user-images.githubusercontent.com/76624203/234501046-37570bcc-f6ab-410d-a536-5a7592188ca8.png)

**Comment by DuVogel87** [comment]
> I have found a solution to the problem: disable the excess graphics card and ensure that only one graphics card is working when you run instant ngp for GTX-1000

Thanks man!!! and congrats ;) 

Can you tell me how to disable the excess graphics card? 

And can you please tell me how to ensure that only one graphics card is working? 

Thanks so far :)

**Comment by chord1412077** [comment]
Enter the Device Manager - Display Adapter, and disable the redundant GPU, leaving only one

**Comment by chord1412077** [comment]
> > I have found a solution to the problem: disable the excess graphics card and ensure that only one graphics card is working when you run instant ngp for GTX-1000
> 
> Thanks man!!! and congrats ;)
> 
> Can you tell me how to disable the excess graphics card?
> 
> And can you please tell me how to ensure that only one graphics card is working?
> 
> Thanks so far :)
Enter the Device Manager - Display Adapter, and disable the redundant GPU, leaving only one

**Comment by chord1412077** [comment]
@lee218llnl I have found a solution to the problem: disable the excess graphics card and ensure that only one graphics card is working when you run instant ngp for GTX-1000

**Comment by MattRM2** [comment]
> Enter the Device Manager - Display Adapter, and disable the redundant GPU, leaving only one

Hi,

There is a way to not have the error and keep all my GPU because my primary display is on a GTX 970 and I have 2x GTX 1070 Ti for rendering ? Or I just need to turn off on of my GTX 1070 Ti ?

Thank you,

Matt

**Comment by Luh1124** [comment]
CUDA_VISIBLE_DEVICES=0 setting single cpu is visible can solve it

**Comment by MattRM2** [comment]
> 

Hi Luh1124,

I tried, only one GPU is selected but still the same error.
Thx for your answer

Matt

**Comment by chord1412077** [comment]
> > Enter the Device Manager - Display Adapter, and disable the redundant GPU, leaving only one
> 
> Hi,
> 
> There is a way to not have the error and keep all my GPU because my primary display is on a GTX 970 and I have 2x GTX 1070 Ti for rendering ? Or I just need to turn off on of my GTX 1070 Ti ?
> 
> Thank you,
> 
> Matt

You can have a try to solve it.Just try to turn off on of your GTX 1070 Ti first .You know,there will be many times to find a successful way.
