### ISSUE TITLE
Record3D and Iphone12

### ISSUE THREAD

**Issue by jdiazram** [NVlabs/instant-ngp#1285]
Hi. Excellent work.
I have a question about using Record3D from Iphone12, not Iphone12 Pro to capture videos for NeRF. I take a video with Iphone12 in Record3D, and then use scripts/record3d2nerf.py with the data captured, but this error appears:

```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1865/1865 [00:00<00:00, 65416.52it/s]
computing center of attention...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1865/1865 [00:00<00:00, 1627288.74it/s]
Traceback (most recent call last):
  File "/home/jdiazram/Documents/cluster-ialab/scripts/instant-ngp/scripts/record3d2nerf-V2.py", line 171, in <module>
    translation, scale = find_transforms_center_and_scale(transforms)
  File "/home/jdiazram/Documents/cluster-ialab/scripts/instant-ngp/scripts/record3d2nerf-V2.py", line 62, in find_transforms_center_and_scale
    translation = min_line_dist(rays_o, rays_d)
  File "/home/jdiazram/Documents/cluster-ialab/scripts/instant-ngp/scripts/record3d2nerf-V2.py", line 59, in min_line_dist
    pt_mindist = np.squeeze(-np.linalg.inv((np.transpose(A_i, [0,2,1]) @ A_i).mean(0)) @ (b_i).mean(0))
  File "<__array_function__ internals>", line 5, in inv
  File "/home/jdiazram/Documents/cluster-ialab/venv/instant-nerf/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/jdiazram/Documents/cluster-ialab/venv/instant-nerf/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```
I try to find the solution, but nothing appears. Is this error for the Iphone12 used, or do I need to use IPhone12 pro o superior?
Thx

**Comment by ZhaoLizz** [comment]
I'm using an iphone14, same error.
