### ISSUE TITLE
GLFW error #65544: X11: Failed to open display :1

### ISSUE THREAD

**Issue by roangel** [NVlabs/instant-ngp#512]
Hi guys,

When I try to run in the provided docker container the instant-ngp nerf with the fox images, sometimes this happens:
![image](https://user-images.githubusercontent.com/21340299/164453007-9597db2f-a480-4e59-a4af-7b7a613c22b9.png)

The very weird thing is that I got it running tons of times, but now I seem to not get it running. Anyone with the same issue?

Thanks.

**Comment by lh2he** [comment]
I have the same issue

**Comment by darlannakamura** [comment]
That happens because you need to provide a display. By default, The container doesn't have a graphical interface associated with it. So, you have two options:
1) if you run the script headless (without the gui) it probably will work: `./build/testbed --scene data/nerf/fox --no-gui`;
2) or you can see what is being displayed running: `xhost local:root`.

**Comment by roangel** [comment]
> That happens because you need to provide a display. By default, The container doesn't have a graphical interface associated with it. So, you have two options:
> 
> 1. if you run the script headless (without the gui) it probably will work: `./build/testbed --scene data/nerf/fox --no-gui`;
> 2. or you can see what is being displayed running: `xhost local:root`.

This solves the problem. Thanks!

**Comment by Vincentqyw** [comment]
``` bash
echo $DISPLAY
```
if it returns `:0.0`, then, 

``` bash
export DISPLAY=:0.0
```

**Comment by ramers87** [comment]
glfw error 65544 x11 the display environment variable is missing 
please how i can fix it?

**Comment by shenqildr** [comment]
export DISPLAY=:1.0 works for me.

**Comment by yiku-bit** [comment]
I try to use mobaxterm to visualize and solved this problem.
https://mobaxterm.mobatek.net/

**Comment by ramers87** [comment]
Did you get a result?

Le ven. 13 oct. 2023, 04:29, Sitian Shen ***@***.***> a
écrit :

**Comment by ShivaramV3223** [comment]
Hi I still have this issue, I tried replicating a code from a paper and stuck with this which gives the following error.
`workspace: /scratch/storage0/be20b032/CMID/runs/cartpole_colours/sac/0
/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/glfw/__init__.py:916: GLFWError: (65544) b'X11: Failed to open display 0.0'
  warnings.warn(message, GLFWError)
/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/glfw/__init__.py:916: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "/scratch/storage0/be20b032/CMID/train.py", line 235, in <module>
    main(cfg)
  File "/scratch/storage0/be20b032/CMID/train.py", line 229, in main
    workspace = W(cfg)
  File "/scratch/storage0/be20b032/CMID/train.py", line 84, in __init__
    self.env.reset()
  File "/scratch/storage0/be20b032/CMID/utils.py", line 119, in reset
    obs = self.env.reset(colour=colour)
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/scratch/storage0/be20b032/CMID/dmc2gym/wrappers.py", line 169, in reset
    obs = self._get_obs(time_step)
  File "/scratch/storage0/be20b032/CMID/dmc2gym/wrappers.py", line 105, in _get_obs
    obs = self.render(
  File "/scratch/storage0/be20b032/CMID/dmc2gym/wrappers.py", line 177, in render
    return self._env.physics.render(
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 215, in render
    camera = Camera(
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 694, in __init__
    if self._physics.contexts.mujoco is not None:
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 525, in contexts
    self._make_rendering_contexts()
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 511, in _make_rendering_contexts
    mujoco_context = wrapper.MjrContext(self.model, render_context)
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 606, in __init__
    ptr = ctx.call(mujoco.MjrContext, model.ptr, font_scale)
  File "/scratch/storage0/be20b032/miniconda3/envs/cmid/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 136, in call
    return func(*args, **kwargs)
mujoco.FatalError: an OpenGL platform library has not been loaded into this process, this most likely means that a valid OpenGL context has not been created before mjr_makeContext was called`
Can anyone give a fix?

**Comment by masoodmortazavi** [comment]
In my case, this only happens when I try to run the program remotely from pycharm :-)
go figure.

**Comment by BaophanN** [comment]
@SitianShen Sorry, what are the exact commands to fix that? I have followed every single of your instruction above but none works. My error message is a bit different: 
For $DISPLAY=localhost:10.0
```
GLFWError: (65550) b'X11: Failed to open display localhost:10.0'
```
I have try to set DISPLAY to :0.0, :1.0, localhost:10.0 and still get the above error. Can anybody help me please?
